// data.js pour TRAD

const tableData = [
    { id: 1,
    code: 'TRAD_00',
    designation: 'Tete de série ',
    qtDefaux: '0',
     totDefaux: '',
      observation: ''
    },
    { id: 2,
     code: 'CONT_01',
    designation: 'Défaut soudure boule /drapeau/trou ',
    qtDefaux: '0',
     totDefaux: '', 
     observation: '' 
    },
    { id: 3,
    code: 'CONT_03',
    designation: 'Défaut mécanique "cassé ou ecrasé',
    qtDefaux: '0',
    totDefaux: '',
     observation: ''
     },
     { id: 4,
        code: 'CONT_05',
        designation: 'Défaut aspect/Forme/couleur...',
        qtDefaux: '0',
        totDefaux: '',
         observation: ''
         },
     
    { id: 5,
         code: 'FOUR_01',
          designation: 'Erreur référence/Errure composant',
           qtDefaux: '0',
            totDefaux: '',
             observation: '' },
    { id: 6,
         code: 'PREP_01',
          designation: 'cambrage mauvais/mal formarté',
           qtDefaux: '0',
            totDefaux: '', 
            observation: '' },
    { id: 7, 
        code: 'PREP_02',
         designation: 'coupe composant mauvaise ',
          qtDefaux: '0',
           totDefaux: '', observation: ''
         },
    { id: 8,
         code: 'SOUD_01',
          designation: 'Mauvaise remontée soudure',
           qtDefaux: '0',
            totDefaux: '', 
            observation: '' 
        },
        { id: 9,
          code: 'SOUD_02',
           designation: 'composant surélevé ou mal plaqué',
            qtDefaux: '0',
             totDefaux: '', 
             observation: '' 
         },
         { id: 10,
          code: 'SOUD_03',
           designation: 'court-circuit soudure trad.',
            qtDefaux: '0',
             totDefaux: '', 
             observation: '' 
         },
         { id: 11,
          code: 'SOUD_04',
           designation: 'soudure manquante/soudure seche',
            qtDefaux: '0',
             totDefaux: '', 
             observation: '' 
         },
         { id: 12,
          code: 'SOUD_05',
           designation: 'carte ou composant tombé dans la vague',
            qtDefaux: '0',
             totDefaux: '', 
             observation: '' 
         },
         { id: 13,
          code: 'SOUD_06',
           designation: 'microbilage',
            qtDefaux: '0',
             totDefaux: '', 
             observation: '' 
         },
         { id: 14,
          code: 'TRAD_01',
           designation: 'Manque composant',
            qtDefaux: '0',
             totDefaux: '', 
             observation: '' 
         },
         { id: 15,
          code: 'TRAD_02',
           designation: 'Sens composant/composant inversé',
            qtDefaux: '0',
             totDefaux: '', 
             observation: '' 
         },
         { id: 16,
          code: 'TRAD_04',
           designation: 'Pastille,piste ou composant abimé(s)/deterioré/cassée',
            qtDefaux: '0',
             totDefaux: '', 
             observation: '' 
         },
         { id: 17,
          code: 'TRAD_06',
           designation: 'Mauvaise soudure manuelle ',
            qtDefaux: '0',
             totDefaux: '', 
             observation: '' 
         },
         { id: 18,
          code: 'TRAD_07',
           designation: 'Broche ou patte repliée',
            qtDefaux: '0',
             totDefaux: '', 
             observation: '' 
         },
         { id: 19,
          code: 'TRAD_08',
           designation: 'Décalage implantation/mal positionnnemenné',
            qtDefaux: '0',
             totDefaux: '', 
             observation: '' 
         },
         { id: 20,
            code: 'TRAD_10',
             designation: 'Bavure PCB non enlevée',
              qtDefaux: '0',
               totDefaux: '', 
               observation: '' 
           },
           { id: 21,
            code: 'TRAD_11',
             designation: 'Collage',
              qtDefaux: '0',
               totDefaux: '', 
               observation: '' 
           },
           { id: 22,
            code: 'TRAD_12',
             designation: 'composnat brulé',
              qtDefaux: '0',
               totDefaux: '', 
               observation: '' 
           },
           { id: 23,
            code: 'TRAD_13',
             designation: 'Etiquette et serialisation/N° Sem',
              qtDefaux: '0',
               totDefaux: '', 
               observation: '' 
           },
  ];
  
  export default tableData;
  